name: Hub
version: '${project.version}'
main: net.pvpmines.Hub
author: KacperM
description: Hub Core made for PVPMines
api-version: 1.19
commands:
  discord:
  twitter:
  store:
  website:
    aliases: [forums]